export const config = {
  avatar: `url(/ben-eris-avatar.JPG)`,
  ogBenEris: `url(/ben-eris-og-final.png)`,
  bgColor: '#18181b',
  textColor: '#d4d4d8',
  iconColor: '#d4d4d8',
  emailColor: '#7b68ee',
  textOpacity: '50%',
  title: 'Ben Eris | Music',
  descriptio: 'An official resource for Ben Eris music, lyrics, news, and contact.',
  firstName: 'BEN',
  lastName: 'ERIS',
  home: 'Music',
  contact: 'Contact',
  lyrics: 'Lyrics',
  mailingList: 'Mailing List',
  siteURL: 'https://beneris.com',
  description: 'Looks You Can\'t Hide EP Out Now',
  links: [
    {
      slug: 'instagram',
      type: 'url',
      link: 'https://www.instagram.com/ben.eris/?hl=en'
    },
    {
      slug: 'apple',
      type: 'url',
      link: 'https://music.apple.com/us/artist/ben-eris/1657881923'
    },
    {
      slug: 'spotify',
      type: 'url',
      link: 'https://open.spotify.com/artist/5ci6j9sW7oZCBKFK8hL4LG?si=ohFLdWQ6ThatYmfz563ZRA'
    },
    {
      slug: 'youtube',
      type: 'url',
      link: 'https://youtu.be/bgO9arGMOg4'
    },
    {
      slug: 'bandcamp',
      type: 'url',
      link: 'https://beneris.bandcamp.com/releases'
    }
  ],
  shyGuy: [
    'I saw it first', 
    'Crash before my eyes', 
    'You\'re never sure', 
    'It\'s a look that you can\'t hide',
    'Looks that you can\'t hide', 
    'break', 
    'I\'m under a curse', 
    'It came in the night', 
    'Can\'t be too sure', 
    'If we don\'t make it on time', 
    'I never make it', 
    'break', 
    'Words go out the window', 
    'When I see you', 
    'Shy guy at the street light', 
    'You\'re waiting for it', 
    'Words go out the window', 
    'When I see you', 
    'Shy guy at the street light',
    'break', 
    'Thinking of her', 
    'Under the light', 
    'I\'m under a power', 
    'Looking into my eyes', 
    'Looking into my eyes', 
    'break', 
    'I\'m scared I would burn', 
    'I\'ve always liked fire', 
    'You\'re something more', 
    'A flame that\'s burning higher', 
    'This flame is burning',
    'break', 
    'Words go out the window', 
    'When I see you', 
    'Shy guy at the street light', 
    'You\'re waiting for it', 
    'Words go out the window', 
    'When I see you', 
    'Shy guy at the street light',
    'break',
    'I know that it won\'t go',
    'If we\'re living a lie',
    'Living a lie',
    'I know that we both know',
    'We\'re waiting outside',
    'Waiting outside',
    'I know that it won\'t go',
    'If we\'re living a lie',
    'Living a lie',
    'I know that we both know',
    'We\'re waiting outside',
    'Waiting outside',
    'break', 
    'Words go out the window', 
    'When I see you', 
    'Shy guy at the street light', 
    'You\'re waiting for it', 
    'Words go out the window', 
    'When I see you', 
    'Shy guy at the street light', 
    'You\'re waiting for it',
    'You\'re waiting for it',
    'You\'re waiting for it',
    'You\'re waiting for it',
    'Waiting',
    'break'
  ],
  soonerOrLater: [
    'Can\'t say what you really want to say',
    'And I don\'t know why',
    'But when I look into your eyes',
    'I could die',
    'Tell me has something changed',
    'Because I don\'t know why I feel this way',
    'break',
    'Don\'t say you don\'t know what I mean',
    'Because you do',
    'And sooner or later you will',
    'Because there\'s nothing more',
    'And sooner or later',
    'break',
    'I did more than my share',
    'And it\'s hold the line',
    'You did not notice',
    'Half the time',
    'Because you don\'t see me',
    'You',
    'You don\'t see',
    'More than tonight',
    'Than tonight',
    'Than tonight',
    'break',
    'You say this is where you want to be',
    'And I don\'t know why',
    'It\'s clear',
    'I\'m not what you had in mind',
    'Tell me the ways to be',
    'That make you want to be with me',
    'break',
    'Don\'t say you don\'t know what I mean',
    'Because you do',
    'And sooner or later you will',
    'Because there\'s nothing more',
    'And sooner or later',
    'break',
    'I did more than my share',
    'And it\'s hold the line',
    'You did not notice',
    'Half the time',
    'Because you don\'t see me',
    'You',
    'You don\'t see',
    'More than tonight',
    'Than tonight',
    'Than tonight',
    'break',
    'I did more than my share',
    'And it\'s hold the line',
    'You did not notice',
    'Half the time',
    'Because you don\'t see me',
    'You',
    'You don\'t see',
    'More than tonight',
    'Than tonight',
    'Than tonight',
    'break'
  ],
  yourRoom: [
    'To the sun and to the moon',
    'Falling stars right in your room',
    'To the south or to the north',
    'Doors are open changing course',
    'break',
    'Falling stars right into your room (falling stars)',
    'Don\'t you feel it\'s a sign we should follow through (feel we should follow through)',
    'Climb the stairs right into your room (climb the stairs)',
    'A place I can\'t deny this is magic and true (ah this is magic and true)',
    'break',
    'Your eyes',
    'So fine I don\'t remember the time',
    'Your smile so shy',
    'You had me gazing up at the sky',
    'Your ceiling spins',
    'I can hardly wait for this to begin',
    'Your heart\'s like mine',
    'A tender touch you hold deep inside',
    'And we cry',
    'break',
    'Candlelight and records spin',
    'Ward against the winter wind',
    'Sit together on your floor',
    'Talk until the early morn',
    'break',
    'Falling stars right into your room (falling stars)',
    'Don\'t you feel it\'s a sign we should follow through (feel we should follow through)',
    'Climb the stairs right into your room (climb the stairs)',
    'A place I can\'t deny this is magic and true (ah this is magic and true)',
    'break',
    'Your eyes',
    'So fine I don\'t remember the time',
    'Your smile so shy',
    'You had me gazing up at the sky',
    'Your ceiling spins',
    'I can hardly wait for this to begin',
    'Your heart\'s like mine',
    'A tender touch you hold deep inside',
    'And we cry',
    'break',
    'I thought you and I',
    'Could leave it all behind',
    'We\'ll go slow',
    'Don\'t have to know',
    'Don\'t have to know',
    'Where we\'ll go',
    'break',
    'Your eyes',
    'So fine I don\'t remember the time',
    'Your smile so shy',
    'You had me gazing up at the sky',
    'Your ceiling spins',
    'I can hardly wait for this to begin',
    'Your heart\'s like mine',
    'A tender touch you hold deep inside',
    'And we cry',
    'break'
  ],
  twoHearts: [
    'If you told me I\'m the only',
    'I would stay',
    'If you hold me when I\'m lonely',
    'I would stay',
    'break',
    'I can\'t feel you',
    'It\'s never enough',
    'break',
    'Waiting on two hearts to find',
    'Trouble lives in mine',
    'Wandering a strange divide',
    'Saying it\'s all fine',
    'break',
    'If I let me just be me',
    'Would you stay?',
    'If I showed you when it hurts me',
    'Would you stay?',
    'break',
    'I can\'t feel you',
    'It\'s never enough',
    'break',
    'Waiting on two hearts to find',
    'Trouble lives in mine',
    'Wandering a strange divide',
    'Saying it\'s all fine',
    'Waiting on two hearts to find',
    'Wandering a strange divide',
    'Saying it\'s all fine',
    'It\'s all fine',
    'It\'s all fine',
    'It\'s all fine',
    'break',
    '(Love,',
    'love',
    'love',
    'love',
    'love)',
    'break',
    'I can\'t feel you (I can\'t feel you)',
    'I can\'t feel you (I can\'t feel you)',
    'I can\'t feel you (I can\'t feel you)',
    'Can\'t feel you',
    'break',
    'Waiting on two hearts to find',
    'Trouble lives in mine',
    'Wandering a strange divide',
    'Saying it\'s all fine',
    'Waiting on two hearts to find',
    'Wandering a strange divide',
    'Saying it\'s all fine',
    'break'
  ],
  sayItAgain: [
    'I couldn\'t let things',
    'Just stay the same',
    'But couldn\'t swallow the change',
    'The change, the change',
    'I knew I had to set out',
    'On my own',
    'But know you\'re never alone',
    'Alone, alone',
    'But know you\'re never alone',
    'break',
    'We both said it was over',
    'I don\'t think it\'s over',
    'How could it be over',
    'Just say it again',
    'Then pull me back in',
    'You pull me right back in',
    'break',
    'And every look that you gave me',
    'On that day',
    'Is getting farther away',
    'Away, away',
    'And though I try to forget',
    'The way',
    'That you would say my name',
    'The way, the way',
    'The way you\'d say my name',
    'break',
    'We both said it was over',
    'I don\'t think it\'s over',
    'How could it be over',
    'Just say it again',
    'Then pull me back in',
    'You pull me right back in',
    'break'
  ],
  betterInWriting: [
    'I\'ve fallen in with strange thoughts',
    'Fallen in these moments with you',
    'I\'ve fallen into strange worlds',
    'Fallen into hopes that you',
    'That you and I',
    'Might just need some time',
    'break',
    'You had said that you wrote it all down',
    'That again you were better in writing',
    'Oh well, guess I\'ll never know',
    'break',
    'Though I\'ve lived here in my dreams',
    'It\'s not the place for me and you',
    'You know I really hate to leave',
    'Leave you in my dreams',
    'Where you and I',
    'Write from time to time',
    'break',
    'You had said that you wrote it all down',
    'That again you were better in writing',
    'Oh well, guess I\'ll never know',
    'break',
    'I tried my very best',
    'To live without and believe the rest',
    'Anything you said that sounded like loving me',
    'I told myself was all I\'d ever need',
    'break',
    'You had said that you wrote it all down',
    'That again you were better in writing',
    'Oh well, guess I\'ll never know'
  ]

}